version: '3'
networks:
  totalrecall:
    external: true

services:
  fluentd:
    build: ./docker/fluentd
    restart: always
    networks: ['totalrecall']
    ports:
      - "24224:24224"

  elasticsearch:
    image: "elasticsearch:2"
    restart: always
    ports: ['127.0.0.1:9200:9200']
    networks: ['totalrecall']
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: "kibana:4"
    restart: always
    networks: ['totalrecall']
    ports: ['127.0.0.1:5601:5601']
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  esdata:
    driver: local
