version: '3'
networks:
  totalrecall: {}

services:
  fluentbit:
    image: fluent/fluent-bit:1.5 
    networks: ['totalrecall']
    command: /fluent-bit/bin/fluent-bit fluent-bit -i tcp -o es -p Host=elasticsearch -p Index=totalrecall -p Type=event -m '*'
    ports: ['127.0.0.1:5170:5170']

  elasticsearch:
    image: "elasticsearch:2"
    restart: always
    ports: ['127.0.0.1:9200:9200']
    networks: ['totalrecall']
    volumes:
    - esdata:/usr/share/elasticsearch/data

  kibana:
    image: "kibana:4"
    restart: always
    networks: ['totalrecall']
    ports: ['127.0.0.1:5601:5601']
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  esdata:
    driver: local
