version: '3'
networks:
  totalrecall:
    external: true

services:
  fluentd:
    build: ./docker/fluentd
    restart: always
    networks: ['totalrecall']
    ports:
      - "24224:24224"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_TAG}
    environment:
      - 'http.host=0.0.0.0'
      - 'transport.host=127.0.0.1'
      - 'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}'
      - 'disovery.type: single-node'
    ports: ['127.0.0.1:9200:9200']
    networks: ['totalrecall']
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_TAG}
    environment: ['ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}']
    ports: ['127.0.0.1:5601:5601']
    networks: ['totalrecall']
    depends_on: ['elasticsearch']

volumes:
  esdata:
    driver: local
