version: '3'
networks:
  totalrecall:
    external: true

services:
  redis:
    image: redis
    restart: always
    ports: ['127.0.0.1:16379:6379']
    networks: ['totalrecall']

  elasticsearch:
    image: "elasticsearch:2"
    restart: always
    ports: ['127.0.0.1:9200:9200']
    networks: ['totalrecall']
    volumes:
    - esdata:/usr/share/elasticsearch/data

  kibana:
    image: "kibana:4"
    restart: always
    networks: ['totalrecall']
    ports: ['127.0.0.1:5601:5601']
    environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200

  collector:
    image: python:3.6
    command: /bin/bash -c 'pip install -r requirements.txt && ./collector.py'
    restart: always
    networks: ['totalrecall']
    ports: ['127.0.0.1:8080:8080']
    working_dir: /var/trc/
    volumes:
    - $PWD/src:/var/trc

  loader:
    image: python:3.6
    command: /bin/bash -c 'pip install -r requirements.txt && ./loader.py'
    restart: always
    networks: ['totalrecall']
    working_dir: /var/trc/
    volumes:
    - $PWD/src:/var/trc

volumes:
  esdata:
    driver: local
